name: android_scheme_search
description: A plugin that search apps according to the given url scheme.
version: 1.0.1
# author: google@alexv525.com
homepage: https://github.com/AlexV525/flutter_android_scheme_search

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.alexv525.android_scheme_search
        pluginClass: AndroidSchemeSearchPlugin
